# This file is for local development using 'tye run'.
# It enables hot-reload for all your .NET services and runs infrastructure in Docker.
name: booking-microservice-dev

# Ingress configuration defines how external traffic reaches your services.
ingress:
  - name: ingress
    bindings:
      - port: 8080 # Main entry point for local development
    rules:
      - path: /
        service: gateway-dev

# All services, both .NET projects and Docker containers, are defined here.
services:
  # .NET Microservices (with hot-reload)
  - name: gateway-dev
    project: ../../src/ApiGateway/src/ApiGateway.csproj
    bindings:
      - protocol: https

  - name: flight-dev
    project: ../../src/Services/Flight/src/Flight.Api/Flight.Api.csproj
    bindings:
      - protocol: https

  - name: identity-dev
    project: ../../src/Services/Identity/src/Identity.Api/Identity.Api.csproj
    bindings:
      - protocol: https

  - name: passenger-dev
    project: ../../src/Services/Passenger/src/Passenger.Api/Passenger.Api.csproj
    bindings:
      - protocol: https

  - name: booking-dev
    project: ../../src/Services/Booking/src/Booking.Api/Booking.Api.csproj
    bindings:
      - protocol: https

  # Infrastructure Services (run via Docker)
  - name: db-dev
    image: mcr.microsoft.com/mssql/server:2022-latest
    env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "@Aa123456"
    bindings:
      - port: 1433

  - name: rabbitmq-dev
    image: rabbitmq:3.13-management
    bindings:
      - port: 5672
      - port: 15672
        containerPort: 15672

  - name: jaeger-dev
    image: jaegertracing/all-in-one:1.57
    bindings:
      - port: 16686

  - name: eventstore-dev
    image: eventstore/eventstore:24.2.0-jammy
    env:
      - name: EVENTSTORE_INSECURE
        value: "true"
    bindings:
      - port: 2113

  - name: mongo-dev
    image: mongo:7.0
    bindings:
      - port: 27017
